import Head from 'next/head'
import { Cousine } from 'next/font/google'
import About from '@/common/components/views/about/About'

const cousine = Cousine({ 
  weight: '400',
  subsets: ['latin'] 
})

export default function Home() {
  return (
    <>
      <Head>
        <title>PORTFOLIO 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cousine.className}>
        <div>
          <About />
        </div>
      </main>
    </>
  )
}
