import Head from 'next/head'
import About from '@/common/components/views/about/About'

export default function Home() {
  return (
    <>
      <Head>
        <title>PORTFOLIO 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <About />
        </div>
      </main>
    </>
  )
}
